layout: post
title: CICD Platform
title-on-all-pages: true
canonical_url: 'https://mrwconsulting.github.io/CiFlex-Samples/''
keywords: >-
  AWS,CDK,CICD,CiFlex,CiFlexCtl,CloudFormation,CodeBuild,CodePipeline,DevOps,Framework,Platform
google_site_verification: OeGS0wbadQfPK17khgBr37EPrl70c4-V_gORkbjV5rg
defaults:
  - scope:
      path: ''
    values:
      layout: default
markdown: kramdown
url: 'https://mrwconsulting.github.io/CiFlex-Samples/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
og_image_title: CICD Platform
